[package]
authors = ["Chris Barrick <cbarrick1@gmail.com>"]
name = "ripl"
version = "0.1.0-master"

[dependencies]
lazy_static = "^0.2"
ordered-float = "0.4.0"
rand = "^0.3"
regex = "^0.2"
unicode-normalization = "^0.1"
