# The official style guide for Ripl.
#
# It was written for `rustfmt` version 0.8.3 and includes values for all
# possible options. It should be reevaluated as new versions of `rustfmt` are
# released. In particular, the "official" style guide for the Rust project is
# currently being developed as an [RFC], and the results of that process should
# be carefully considered.
#
# [RFC]: https://github.com/rust-lang-nursery/fmt-rfcs
#
# Changelog:
# - 2017-04-13: Created by cbarrick

# Global style
hard_tabs = false
max_width = 100
newline_style = "Unix"
tab_spaces = 4

# Control flow
control_brace_style = "AlwaysSameLine"
indent_match_arms = true
match_block_trailing_comma = true
single_line_if_else_max_width = 50
wrap_match_arms = true

# Functions
chain_indent = "Block"
chain_one_line_max = 60
closure_block_indent_threshold = 7
fn_args_density = "Tall"
fn_args_layout = "Block"
fn_args_paren_newline = true
fn_brace_style = "SameLineWhere"
fn_call_style = "Block"
fn_call_width = 60
fn_empty_single_line = true
fn_return_indent = "WithWhereClause"
fn_single_line = false

# Arrays, enums, and structs
item_brace_style = "SameLineWhere"
array_layout = "Block"
array_width = 60
single_line_if_else = true
struct_lit_multiline_style = "PreferSingle"
struct_lit_style = "Block"
struct_lit_width = 18
struct_variant_width = 35

# Generics and `where` clauses
generics_indent = "Block"
generics_style = "Rfc"
where_density = "Tall"
where_indent = "Block"
where_layout = "Mixed"
where_pred_indent = "Block"
where_style = "Rfc"

# Comments
comment_width = 80
normalize_comments = true
wrap_comments = true

# Other
condense_wildcard_suffices = false
disable_all_formatting = false
error_on_line_overflow = true
force_explicit_abi = true
force_format_strings = false
format_strings = false
impl_empty_single_line = true
reorder_imported_names = true
reorder_imports = false
report_fixme = "Never"
report_todo = "Never"
skip_children = false
space_after_bound_colon = true
space_after_type_annotation_colon = true
space_before_bound = false
space_before_type_annotation = false
spaces_around_ranges = false
spaces_within_angle_brackets = false
spaces_within_parens = false
spaces_within_square_brackets = false
take_source_hints = true
trailing_comma = "Vertical"
type_punctuation_density = "Wide"
use_try_shorthand = false
verbose = false
write_mode = "Replace"
